# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0ead3fbf8e47d56a5749525e48cc478"
name = "A360 Discounts"
handle = "a360-discounts-app"
application_url = "https://calendar-largely-earliest-bb.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aromacrtest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://calendar-largely-earliest-bb.trycloudflare.com/auth/callback",
  "https://calendar-largely-earliest-bb.trycloudflare.com/auth/shopify/callback",
  "https://calendar-largely-earliest-bb.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
